feat: add test for certificate block production
topos-protocol/local-erc20-messaging-infra pull request #42
Opened 2023-12-11 14:02 UTC by atanmarko

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Additions and Changes

Please explain in detail, if applicable, which changes you performed in the PR and link them to issues. (If not applicable you can remove this whole section)

### Bug fix (non-breaking change which fixes an issue)

### New feature (non-breaking change which adds functionality)

## Breaking changes

Please explain in detail which changes are breaking changes in the PR. (If not applicable you can remove this whole section)

## PR Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added or updated tests that comprehensively prove my change is effective or that my feature works

2023-12-12 13:42 UTC, Freyskeyd requested changes

2023-12-12 13:42 UTC, Freyskeyd commented on tests/network.sh
> +fi
You don't need that

2023-12-12 13:42 UTC, Freyskeyd commented on tests/network.sh
> +
You can put a `set -e` here

2023-12-12 13:42 UTC, Freyskeyd commented on tests/test_cert_production.sh
> +
Same `set -e` for error handling

2023-12-12 13:42 UTC, Freyskeyd commented on tests/test_cert_production.sh
> +
here you can just `source network.sh`

2023-12-12 13:42 UTC, Freyskeyd commented on tests/test_cert_production.sh
> +$LOCAL_ERC20_HOME/tests/network.sh is_running
```suggestion
is_running
```

2023-12-12 13:42 UTC, Freyskeyd commented on tests/test_cert_production.sh
> +    $LOCAL_ERC20_HOME/tests/network.sh start
```suggestion
    start_network
```

2023-12-12 13:42 UTC, Freyskeyd commented on tests/test_cert_production.sh
> +    $LOCAL_ERC20_HOME/tests/network.sh stop
```suggestion
    stop_network
```

2023-12-12 13:42 UTC, Freyskeyd commented on tests/test_cert_production.sh
> +fi
The test should return `0` or `1`

2023-12-12 13:47 UTC, atanmarko commented on tests/test_cert_production.sh
> +fi
Right in case of error it would return 1, if everything passes it returns 0

2023-12-12 14:14 UTC, atanmarko commented on tests/network.sh
> +fi
Well start network manually in the separate workflow step - so not for every test script we execute. Hence I think we need it

2023-12-12 15:02 UTC, atanmarko commented on tests/network.sh
> +fi
I've put this in a separate file and common `utils.sh` file

2023-12-14 11:11 UTC, Freyskeyd approved these changes
Approve with some nitpicks

2023-12-14 11:11 UTC, Freyskeyd commented on tests/network.sh
> +fi
Break line at the end of file.

2023-12-14 11:11 UTC, Freyskeyd commented on subnet-topos.yml
> +      topos-node-4:
The `topos-node-4` isn't always the last one started or healthy, if it was your expectation it doesn't guarantee it.

2023-12-14 11:11 UTC, Freyskeyd commented on scripts/polygon_edge_healthcheck.sh
> +	exit 1;
```suggestion
    exit 1;
```

2023-12-14 11:12 UTC, atanmarko commented on subnet-topos.yml
> +      topos-node-4:
It has different health condition to start producing blocks, meaning that all other nodes are already up

2023-12-14 11:44 UTC, merged